### ISSUE TITLE
Jeff T - Need a second set of eyes on my code too make sure I'm not to far off the reservation.

### ISSUE THREAD

**Issue by ilikesounds** [codefellows/seattle-201n3#28]
## When submitting a request for lab help, please include the following information:

1. What assignment are you working on?

N10 - Adding render function to push to table elements

2. What is the unexpected outcome of your code?

The code is working. HTML elements are being created as expected,but I'm concerned that, I'm utilizing an inefficient method of creating the elements and I would appreciate a review before I use this "method" on other parts of my code. The code snippet below is how I plan to render my table in sections. Below is the header section. 
 
``` javascript

function renderTH() {
  var tHeader = document.createElement('thead');
  var dataTable = document.createElement('table');
  sD.appendChild(dataTable);
  dataTable.id = 'dataTable';
  var tHR = [];
  var eTD = [];
  for (var thr = 0; thr < 2; thr++) {
    tHR.push(document.createElement('tr'));
    eTD.push(document.createElement('td'));
    eTD[thr].className = 'emptyTableData';
    tHR[thr].appendChild(eTD[thr]);
    tHeader.appendChild(tHR[thr]);
  };
  tHeader.id = 'tableHeader';
  tHR[0].id = 'storeNameRow';
  tHR[1].id = 'storeStatsRow';
  dataTable.appendChild(tHeader);
};
```
3. What is the expected outcome of your code?

**Comment by sjschmidt44** [comment]
Totally fine! As discussed, with how you're implementing the overall table, this is great.
