### ISSUE TITLE
function daFuq() {

### ISSUE THREAD

**Issue by jurrish** [codefellows/seattle-201n3#30]
## When submitting a request for lab help, please include the following information:

1. What assignment are you working on?
cookie lab

2. What is the unexpected outcome of your code?
my hours from my time array are not appending.

  - Please include any pointers, such as line numbers.
44-57
  - Please include any error messages or other output associated with your issue.
no.
  - Please include any relevant description and code snippets (using Markdown Syntax for your code blocks).
    - ```var hoursRow = document.createElement('tr');//creating a tr element and saving it as a variable named hoursRow so that we can use .appendChild later.
  // var tableHeader = document.createElement('tr');//do i need this?
  var emptyCell = document.createElement('th');//creating an empty data box as a header for the row
  hoursRow.appendChild(emptyCell);//adding the th emptyCell to the hours row that was defined earlier
  for (var i = 0; i < timeArray; i++) {//during this time, we are adding times in the timeArray as our hour row
    tableHeader.textContent = timeArray[i];//at each iteration add the indexed value of timeArray(whichever hour it happens to be in within the array)
    hoursRow.appendChild(tableHeader);//append that shit to the hoursRow
  }
  var totalHeader = document.createElement('th');//creating a total header to append to the end of the hours row
  totalHeader.textContent = 'Total';
  hoursRow.appendChild(totalHeader);
  tableEl.appendChild(hoursRow);```

3. What is the expected outcome of your code?

**Comment by jurrish** [comment]
var hoursRow = document.createElement('tr');//creating a tr element and saving it as a variable named hoursRow so that we can use .appendChild later.
  // var tableHeader = document.createElement('tr');//do i need this?
  var emptyCell = document.createElement('th');//creating an empty data box as a header for the row
  hoursRow.appendChild(emptyCell);//adding the th emptyCell to the hours row that was defined earlier
  ``` javascript
for (var i = 0; i < timeArray; i++) {
    tableHeader.textContent = timeArray[i]; 
    hoursRow.appendChild(tableHeader);
  }
  var totalHeader = document.createElement('th');
  totalHeader.textContent = 'Total';
  hoursRow.appendChild(totalHeader);
  tableEl.appendChild(hoursRow);  
```

**Comment by sjschmidt44** [comment]
``` javascript
var hoursRow = document.createElement('tr');
var emptyCell = document.createElement('th');
hoursRow.appendChild(emptyCell);

for (var i = 0; i < timeArray; i++) {
  // Where is `tableHeader` defined? It's probably showing as undefined here.
  tableHeader.textContent = timeArray[i]; 
  hoursRow.appendChild(tableHeader);
}
var totalHeader = document.createElement('th');
totalHeader.textContent = 'Total';
hoursRow.appendChild(totalHeader);
tableEl.appendChild(hoursRow); 
```
Check my comment above... I don't see where that variable is defined, so you're not really appending anything to your array.

**Comment by sjschmidt44** [comment]
Glad you got your debugging on, and figured it out!
