### ISSUE TITLE
Jeff T - tbody tag is failing to render on HTML document

### ISSUE THREAD

**Issue by ilikesounds** [codefellows/seattle-201n3#33]
## When submitting a request for lab help, please include the following information:

1. What assignment are you working on?

N10

2. What is the unexpected outcome of your code?

The function that is defining my table is failing to render the tbody tag, but the thead and tfooter tags on either side of it in the function render correctly. When I log the tableEl[2] element, I see that tbody is created, but it is not appended for some reason.

``` javascript
var sD = document.getElementById('storesDiv');

var tableEl = [
  document.createElement('table'),
  document.createElement('thead'),
  document.createElement('tbody'),
  document.createElement('tfoot')
];

function defineTable() {
  sD.appendChild(tableEl[0]);
  tableEl[0].appendChild(tableEl[1]);
  tableEl[0].appendChild(tableEl[2]);
  tableEl[0].appendChild(tableEl[3]);
  tableEl[0].id = 'dataTable';
  tableEl[1].id = 'dataHeader';
  tableEl[2].id = 'dataBody';
  tableEl[3].id = 'dataFooter';
};
```

3. What is the expected outcome of your code?

The expected outcome would be for all three table elements to be created and appended to the table element created in the function.

**Comment by sjschmidt44** [comment]
Weird side effect... I'm not sure why using these element selectors in an array is causing issues.
