### ISSUE TITLE
J Torres - Need help understanding how to iterate over the number of items within an object array

### ISSUE THREAD

**Issue by ilikesounds** [codefellows/seattle-201n3#34]
## When submitting a request for lab help, please include the following information:

1. What assignment are you working on?

n10

2. What is the unexpected outcome of your code?
the function that I wrote to populate my table header is not firing. I believe it is because I'm trying to use the Stores object to iterate over within my function. I have been unable to log anything in the console log and I receive the following error when I attempt to fire it manually from the browser console. Uncaught TypeError: pike.renderStoreStat is not a function(…)(anonymous function) 

``` javascript
Store.renderStoreStat = function(obj) {
  var nameRow = document.getElementById('storeNameRow');
  var sNRow = [];
  for (stores in Store) {
    sNRow.push(document.createElement('td'));
    var idName = obj.name;
    idName = idName.replace(/\s+/g, '');
    sNRow.id = idName;
    tableEl.appendChild(sNRow[stores]);
  }
};
```

3. What is the expected outcome of your code?
The expected outcome is that my code will populate my table header with the store names.

**Comment by sjschmidt44** [comment]
'Store.renderStoreStat(pike)` should do the trick for you.
