### ISSUE TITLE
Jonathan - images won't click

### ISSUE THREAD

**Issue by spamalope01** [codefellows/seattle-201n3#42]
## When submitting a request for lab help, please include the following information:

1. What assignment are you working on?
What is this, N13, i think? 

2. What is the unexpected outcome of your code?
Images are displaying as expected.  They even show new images upon page refresh.  However, when I click on any image, nothing happens.  I can't even get a console.log to display...so something is happening (i'm guessing) early on in the OnClick event.  maybe it's not being called?  I'm not getting any console errors.  I even tried moving the ```imgRank.imgEls.addEventListener('click', imgRank.onClick);``` up from outside the object into the on click section...didn't work. 

Here's the onClick portion of my code, in my case, imgRank = the sample's productRank object.  ```  onClick: function() {
    if (event.target.id === imgRank.leftImg.name || event.target.id === imgRank.rightImg.name || event.target.id === imgRank.midImg.name) {
      imgRank.tallyClicks(event.target.id);

      if(imgRank.totalClicks % 15 === 0) {
        imgRank.imgEls.removeEventListener('click', imgRank.onClick());
        imgRank.showButton();
      }
      imgRank.displayImages();
    } else {
      alert('click on an image');
    }
  }
};

imgRank.imgEls.addEventListener('click', imgRank.onClick);
imgRank.displayImages(); ```

Also, if i keep the 'else' alert active...it fires anytime i click anything, so that tells me that the error is somewhere above it and below the onclick starting line, but i can't for the life of me figure it out.  

3. What is the expected outcome of your code?
I'm expecting it to allow me to click an image and have a new set of images display, while the click is registered to the corresponding image as a vote.

**Comment by sjschmidt44** [comment]
Updating the code block to show correctly.

``` javascript
onClick: function() {
  if (event.target.id === imgRank.leftImg.name || event.target.id === imgRank.rightImg.name || event.target.id === imgRank.midImg.name) {
    imgRank.tallyClicks(event.target.id);

    if(imgRank.totalClicks % 15 === 0) {
      imgRank.imgEls.removeEventListener('click', imgRank.onClick());
      imgRank.showButton();
    }
    imgRank.displayImages();
    } else {
    alert('click on an image');
    }
  }
};

imgRank.imgEls.addEventListener('click', imgRank.onClick);
imgRank.displayImages();
```

**Comment by sjschmidt44** [comment]
It looks like you are missing an opening bracket on the 2nd line, after your `if()`, and have one too many closing brackets in there, just before the `else{}`

I'm also not sure if the `imgRank.displayImages()` call about half way down is in the right place.

**Comment by spamalope01** [comment]
i have that opening bracket on the 2nd line (in the code block above, it was off the page)...it's right after || event.target.id === imgRank.midImg.name). 

so i think i have all my opening and closing brackets accounted for....i moved the imgRank.displayImages(); to just under the first 'if', right after imgRank.tallyClicks(event.target.id)....because it seemed logical to put it there....since w'ere still in the first if...if the id's equal any of the image names, then tally clicks and display images again.... but that's not getting it.

**Comment by sjschmidt44** [comment]
Check this out...  

``` javascript
  onClick: function() {
    if (event.target.id === imgRank.leftImg.name || event.target.id === imgRank.rightImg.name || event.target.id === imgRank.midImg.name) {
      imgRank.tallyClicks(event.target.id);

      if(imgRank.totalClicks % 15 === 0) {
        imgRank.imgEls.removeEventListener('click', imgRank.onClick());  // You don't need to call the onClick here. The event listener will do that for you.
        imgRank.showButton();
      }
      imgRank.displayImages(); // You were close with this, but I think you had one too many brackets to start.
    } else {
      var errorMsg = document.getElementById('missedTarget');
      var errorContent = errorMsg.innerHTML;  // This line is not necessary.
       errorMsg.innerHTML = '<p>' + 'You need to click on an image.' + '</p>';
    }
  }
```
