### ISSUE TITLE
I can payz rent: logic to expand initial search range incrementally until minimum results array index length is met

### ISSUE THREAD

**Issue by patrickjcolgan** [codefellows/seattle-201n3#45]
## When submitting a request for lab help, please include the following information:

1. What assignment are you working on?
Cost of Living project

2. What is the unexpected outcome of your code?
We have included a function that checks for and avoids duplicates in our ``matchInput`` function. We need to find a way to expand our search range if there arent five objects in the results array. Our current attempts loop endlessly. 
-we have used a while loop and a foor loop iterating over ``resultsArray.length < 5``
-matchInut is called in an eventListener above this code.
    ``` javascript
var resultsArr = [];

function checkDupArray (array1, array2){
  if (array1.indexOf(array2) === -1){
    array1.push(array2);
    console.log('new array is ' + array1);
  } else if (array1.indexOf(array2) > -1){
    console.log(array2 + 'already exists in the array');
  }
}

matchInput = function(range){
  userInput = parseInt(userInput);
  var lowerIncomeRange = userInput - parseInt(range);
  var higherIncomeRange = userInput + parseInt(range);
  console.log(lowerIncomeRange);
  console.log(higherIncomeRange);

    for (var i = 0; i < allMetro.length; i++){
      if (lowerIncomeRange < allMetro[i].income && allMetro[i].income < higherIncomeRange){
        checkDupArray(resultsArr, allMetro[i].name);
      }
    }
  };
    ```

3. What is the expected outcome of your code?
We want the code to expand the search range incrementally if the min number of results are not present in the resultsArray.

**Comment by sjschmidt44** [comment]
Have you validated that this actually works?
``` javascript
function checkDupArray (array1, array2){
  if (array1.indexOf(array2) === -1){
    array1.push(array2);
    console.log('new array is ' + array1);
  } else if (array1.indexOf(array2) > -1){
    console.log(array2 + 'already exists in the array');
  }
}
```

By my testing, you can't validate a nested array, for example `var arr = [[1, 2], [3, 4]];`, by doing something like `arr.indexOf([3, 4]);`. I think you need to look for specific values inside of a nested array if you want to use `indexOf()`.

That might be your first issue?

**Comment by patrickjcolgan** [comment]
Yes. For example, before the ``checkDupArray`` function, if user input 80000, it would return one instance of Manhattan. If user clicks submit again w/o refreshing the page, there would be two instances of Manhattan. Now this does not happen. 
(This example was when we had a ``matchInput`` range of 1000 above and below the input value. Now it is at 5000.)

**Comment by patrickjcolgan** [comment]
Unless I am missing something, I may have figured out PART of the issue. I added ``&& array1.length < 5)`` in the ``checkDupArray function``

Then, I input 45k twice. Here's my console results: 
```resultsArr
["ArlingtonTX", "AtlantaGA", "AugustaGA", "AustinTX", "BatonRougeLA"]
results.js:41 40000
results.js:42 50000
results.js:33 ArlingtonTXalready exists in the array
results.js:33 AtlantaGAalready exists in the array
results.js:33 AugustaGAalready exists in the array
results.js:33 AustinTXalready exists in the array
results.js:33 BatonRougeLAalready exists in the array
resultsArr
["ArlingtonTX", "AtlantaGA", "AugustaGA", "AustinTX", "BatonRougeLA"]```

Therefore, I believe this avoids duplicates in the array AND, the following code allows for making sure the array reaches a length of five. 
``` javascript
function checkDupArray (array1, array2){
  if (array1.indexOf(array2) === -1 && array1.length < 5){
    array1.push(array2);
    console.log('new array is ' + array1);
    if (array1.length < 5){
      matchInput(10000);
    } if (array1.length < 5){
      matchInput(15000);
    } if (array1.length < 5){
      matchInput(20000);
    }
  } else if (array1.indexOf(array2) > -1){
    console.log(array2 + 'already exists in the array');
  }
}```
