### ISSUE TITLE
How to access the lat and lng object literal/neighbors array?

### ISSUE THREAD

**Issue by CodyHulsey** [codefellows/seattle-201n3#46]
## When submitting a request for lab help, please include the following information:

1. What assignment are you working on?
Cost of Living Project
2. What is the unexpected outcome of your code?
Can't seem to zoom into each marker after it has dropped. In the Javascript console I am seeing "setCenter: not a LatLng or LatLngLiteral: not an Object".
    ```
var neighbors = [
{lat: 41.081445, lng: -81.519005},
{lat: 42.652579, lng: -73.756232},
{lat: 61.218056, lng: -149.900278},
{lat: 32.735687, lng: -97.108066},
{lat: 35.595058, lng: -82.551487},
{lat: 33.748995, lng: -84.387982},
{lat: 33.473498, lng: -82.010515},
];


var markers = [];
var map;

function initMap() {
  map = new google.maps.Map(document.getElementById('googlemapsbackground'), {
    zoom: 5,
    center: {lat: 39.8282, lng: -98.5795}
  });
}

window.onload = function drop() {
  clearMarkers();
  for (var j = 0; j < neighbors.length; j++) {
    // map.setCenter(neighbors[j].lat, neighbors[j].lng);
    addMarkerWithTimeout(neighbors[j], j * 10000);
    // map.setCenter(("lat: " + neighbors[j].lat), ("lng: " + neighbors[j].lng));
    // map.setCenter({lat: 41.079933, lng: -80.66321});
    // map.setCenter({lat: 34.225726, lng: -77.94471});
  }
}

function addMarkerWithTimeout(position, timeout) {
  window.setTimeout(function() {
    markers.push(new google.maps.Marker({
      position: position,
      map: map,
      animation: google.maps.Animation.DROP
    }));
  }, timeout);
}

function clearMarkers() {
  for (var j = 0; j < markers.length; j++) {
    markers[j].setMap(null);
  }
  markers = [];
}

    ```

3. What is the expected outcome of your code?
On load I would like the map to zoom into each location once a marker is dropped. Then once another marker is dropped, it zooms to that location. I tried a variety of different things (see commented out code). To my understanding, the var neighbors array is creating an object literal (see curly brackets). My group and I were thinking that we could just have the center change every 10 seconds or so and have it synced to the neighbors array, but it's giving us issues.

**Comment by sjschmidt44** [comment]
Cody, I'm not that familiar with Google Maps to know if you can do that you're wanting to do (by my interpretation). Did you find something online that indicates you can do that?

**Comment by CodyHulsey** [comment]
Scott, I haven't seen anyone do this on a website unfortunately. Maybe it's not possible?

**Comment by CodyHulsey** [comment]
Figured it out!
