### ISSUE TITLE
I can payz rent: populating data array for bar chart (and other charts later on)

### ISSUE THREAD

**Issue by patrickjcolgan** [codefellows/seattle-201n3#47]
## When submitting a request for lab help, please include the following information:

1. What assignment are you working on?
I can payz rent project

2. What is the unexpected outcome of your code?
I want to populate the data array of my bar chart. However, the way we have our code written thus far, I am not able to do it the way it was done in the marketing-app assignment. 

we have a results array that populates the city names here: 
    ``` javascript
matchInput = function(range) {
  userInput = parseInt(userInput);
  var lowerIncomeRange = userInput - parseInt(range);
  var higherIncomeRange = userInput + parseInt(range);
  for (var i = 0; i < allMetro.length; i++) {
    if (lowerIncomeRange < allMetro[i].income && allMetro[i].income < higherIncomeRange) {
      checkDupArray(resultsArr, allMetro[i].name);
      console.log('dupestate succssfully processed');
      if (dupeState === true) {
        resultsArr.push(allMetro[i].name);
        resultsIncomeArr.push(allMetro[i].income);
        console.log(dupeState);
        console.log(resultsArr.length);
      }
    }
  }
};
    ```
Jeff is currently working on generating a randomizer that populates a new array that we can use in the ``labels`` section of our bar chart, however, this array only has city names/locations. I am unsure how I should pull cost of living data in a way that can be pushed into the bar chart's data array. CURRENTLY, I have added a new ``resultsIncomeArr`` to collect the income data. 

It populates with the correct data, now, how the heck do I get that data into the bar chart? here's what I've tried. Console says "i is undefined"
``` javascript
var dupeState;
var resultsArr = [];
var resultsIncomeArr = [];

var data = {
    labels: resultsArr, // change to randomArr once we make it,
    datasets: [
        {
            label: "My First dataset",
            backgroundColor: "rgba(255,99,132,0.2)",
            borderColor: "rgba(255,99,132,1)",
            borderWidth: 1,
            hoverBackgroundColor: "rgba(255,99,132,0.4)",
            hoverBorderColor: "rgba(255,99,132,1)",
            data: [],
        }
    ]
};
//Bar Chart - push data into array
barChartData = function() {
  data.datasets[0].data[i] = resultsIncomeArr.income;
}
barChartData();
//Bar Chart - create
barChartResults = function(){
  var ctx = document.getElementById('barCanvas').getContext('2d');
        var barCanvas = new Chart(ctx, {
					type: 'bar',
					data: data,
				});
};```





3. What is the expected outcome of your code?
I want to populate the data array of my bar chart. However, the way we have our code written thus far, I am not able to do it the way it was done in the marketing-app assignment.

**Comment by sjschmidt44** [comment]
Your `barChartData()` method needs a for loop to iterate over the `resultsIncomeArr`. I'm not totally sure this syntax is correct, but I think you're looking for something like this:
``` javascript
barChartData = function() {
  for (idx in resultsIncomeArr) {
    data.datasets[0].data[idx] = resultsIncomeArr[idx].income;
  }
}
```

**Comment by patrickjcolgan** [comment]
Figured out most of it (hopefully, what jeff made doesn't negate all my efforts :))
I had to take off ``.income`` from ``resultsIncomeArr[idx].income``

Thanks for the help. 
I will leave this issue open though, since there are still some problems. But I'll work on it myself a bit before I ask another question.
